// SSH remote deployment — thin Tauri command wrappers over clawno_core::ssh.
//
// The 5 shared deploy-step commands are generated by the macro.
// Desktop uses `include_system_fallback: true` so check_node_script
// includes apt/yum fallback for servers.

clawno_core::define_ssh_deploy_commands!(include_system_fallback: true);
