// SSH remote deployment & management — thin Tauri command wrappers over
// clawno_core::ssh.
//
// The 5 shared deploy-step commands are generated by the macro.
// Mobile uses `include_system_fallback: false` — no apt/yum fallback.
// The additional management commands below are mobile-only.

clawno_core::define_ssh_deploy_commands!(include_system_fallback: false);

// ── Remote management commands (mobile-only) ────────────────────────────────

#[tauri::command]
pub async fn ssh_stop_instance(args: SshArgs) -> StepResult {
    if let Err(e) = ssh::validate_ssh_args(&args) {
        return StepResult::err(e);
    }
    let script = ssh::cmd_stop_gateway();
    match ssh::ssh_exec(&args, &script).await {
        Ok((_, out)) if out.contains("gateway-stopped") => {
            StepResult::ok("gateway-stopped".to_string())
        }
        Ok((_, out)) => StepResult::err(format!("stop-failed:{}", last_line(&out))),
        Err(e) => StepResult::err(e),
    }
}

#[tauri::command]
pub async fn ssh_start_instance(args: SshArgs) -> StepResult {
    if let Err(e) = ssh::validate_ssh_args(&args) {
        return StepResult::err(e);
    }
    let script = ssh::cmd_start_gateway();
    match ssh::ssh_exec(&args, &script).await {
        Ok((_, out)) if out.contains("gateway-started") => {
            StepResult::ok("gateway-started".to_string())
        }
        Ok((_, out)) => StepResult::err(format!("start-failed:{}", last_line(&out))),
        Err(e) => StepResult::err(e),
    }
}

#[tauri::command]
pub async fn ssh_restart_instance(args: SshArgs) -> StepResult {
    if let Err(e) = ssh::validate_ssh_args(&args) {
        return StepResult::err(e);
    }
    let script = ssh::cmd_restart_gateway();
    match ssh::ssh_exec(&args, &script).await {
        Ok((_, out)) if out.contains("gateway-restarted") => {
            StepResult::ok("gateway-restarted".to_string())
        }
        Ok((_, out)) => StepResult::err(format!("restart-failed:{}", last_line(&out))),
        Err(e) => StepResult::err(e),
    }
}

#[tauri::command]
pub async fn ssh_configure_api_key(args: SshArgs, provider: String, api_key: String) -> StepResult {
    if let Err(e) = ssh::validate_ssh_args(&args) {
        return StepResult::err(e);
    }
    let script = ssh::cmd_configure_api_key(&provider, &api_key);
    match ssh::ssh_exec(&args, &script).await {
        Ok((_, out)) if out.contains("api-key-configured") => {
            StepResult::ok("api-key-configured".to_string())
        }
        Ok((_, out)) => StepResult::err(format!("api-key-failed:{}", last_line(&out))),
        Err(e) => StepResult::err(e),
    }
}

#[tauri::command]
pub async fn ssh_kill_switch(args: SshArgs) -> StepResult {
    if let Err(e) = ssh::validate_ssh_args(&args) {
        return StepResult::err(e);
    }
    let script = ssh::cmd_stop_gateway();
    match ssh::ssh_exec(&args, &script).await {
        Ok((_, out)) if out.contains("gateway-stopped") => {
            StepResult::ok("kill-switch-activated".to_string())
        }
        Ok((_, out)) => StepResult::err(format!("kill-switch-failed:{}", last_line(&out))),
        Err(e) => StepResult::err(e),
    }
}
